config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#index'


  resources :list, only: %i(new create edit update destroy) do
    # 以下は、右記と同義。  resources :card, only: %i(new create show edit update destroy)
    resources :card, except: %i(index) do
      put :sort
    end
 end
  resources :user, only: %i(edit update)

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  include RankedModel
  ranks :row_order, with_same: :list_id

  belongs_to :list

  validates :title, length:{in: 1..255}
  validates :memo, length:{maximum: 1000}
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy

  validates :title, length: {in: 1..255}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, {presence: true, 
                    length: {maximum: 20}
                  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ==========ここから編集する==========
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  # ==========ここから編集する==========

end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: %i(show edit update destroy)

  def new
    @card = Card.new
    @list = List.find(params[:list_id])
  end

  def create
    @card = Card.new(card_params)
    @card.order = Card.where(list_id: params[:list_id]).maximum(:order).to_i + 1    # Listにカードが存在しない場合、nilが返却されるので問題なく動くようにto_iする
    if @card.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def show
  end

  def edit
    @lists = List.where(user: current_user)
    @cards = Card.where(list_id: params[:list_id]).rank(:row_order)
  end

  # TODO: 実装できていないこと
  # １：カードの編集画面からリストを変更した際に、row_orderが更新されず、変な部分にカードが移動してしまう
  # edit画面にてリストの並び替えを行なった場合、row_orderを最大値に更新し、最下部に来るようにしたい
  # card_paramsに、以下のような形でrow_order_positionに最大値を設定できればいけるかも？
  def update
    # リストに変更があった場合、orderも更新
    if params[:list_id] != card_params[:list_id]
      @card.order = Card.where(list_id: card_params[:list_id]).maximum(:order).to_i + 1    # Listにカードが存在しない場合、nilが返却されるので問題なく動くようにto_iする
    # 並び順に変更があった場合
    elsif @card.order != card_params[:order]
      order_after = card_params[:order].to_i
      # 変更前のorder > 変更後のorder
      if @card.order > order_after
        (order_after..@card.order-1).each {|n| 
          @card_order = Card.find_by(list_id: params[:list_id], order: n)
          @card_order.update_attributes(order: n+1)
        }
      # 変更前のorder < 変更後のorder
      elsif @card.order < order_after
        (@card.order+1..order_after).each {|n| 
          @card_order = Card.find_by(list_id: params[:list_id], order: n)
          @card_order.update_attributes(order: n-1)
        }
      end
      @card.order = card_params[:order]
    end

    if @card.update_attributes(card_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    # 削除されたカードよりorderが大きいカードは、orderを-1する
    cards = Card.where(list_id: params[:list_id], order: @card.order+1..Float::INFINITY)
    cards.each { |card|
      card.update_attributes(order: card.order-1)
    }
    @card.destroy
    redirect_to :root
  end

  def sort
    card = Card.find(params[:card_id])
    card.update(card_params)
    render body: nil
  end

  
  private
    def card_params
      params.require(:card).permit(:title, :memo, :list_id, :order, :row_order_position)
    end

    def set_card
      @card = Card.find(params[:id])
    end

end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: %i(edit update destroy)

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @list.update_attributes(list_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to :root
  end

  private
  def list_params
    params.require(:list).permit(:title).merge(user: current_user)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.where(user: current_user).order(:created_at)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: %i(edit update)
  
  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/card/edit.html.erb
<div class="cardeditPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div>
      <div class="cardeditForm_memo">
        <label>リスト名</label>
        <%= select :card, :list_id, @lists.map{ |l| [l.title, l.id] }, {}, { class: 'form-control' } %>
      </div>
      <%= f.hidden_field :order, value: @card.order %>
      <div class="text-center"><%= f.submit "更新する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/card/new.html.erb
<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardnewForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
      <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/card/show.html.erb
<div class='carddetailPage'>
  <div class="container">
    <div class="cardContents">
      <div class="cardContents_title">
        <div>タイトル</div>
        <h2><%= @card.title %></h2>
      </div>
      <div class="cardContents_memo">
        <div>メモ</div>
        <div><%= @card.memo %></div>
      </div>
      <div class="cardContents_listStatus">
        <div>リスト名</div>
        <div><%= @card.list.title %></div>
      </div>
      <div class="cardContents_btnArea">
        <%= link_to '編集する', edit_list_card_path(@card.list, @card), class: "edit_btn" %>
        <%= link_to '削除をする', list_card_path(@card.list, @card), method: :delete, class: "text-danger delete_btn", data: { confirm: "このカードを削除して大丈夫ですか?" } %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kanban</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# ==========ここから追加する========== %>
    <%= render 'partial/header' if current_user %>
    <%# ==========ここまで追加する========== %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/list/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :update }, html: { class: 'listForm' }, local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/list/new.html.erb
<div class="listnewPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :create }, class: "new_list", local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/partial/_header.html.erb
<header class="header">
  <nav class="nav">
    <ul class="header_menu">
      <li class="nav-link"><%= link_to "#{current_user.name}さん", edit_user_path(current_user) %></li>
      <li class="header_menu_title"><%= link_to "kanban", root_path, class: "nav-link" %></li>
      <li>
        <ul class="header_menu_inner">
          <%# リストを作成するリンクは今後開発していくので、今は"#"にしておきます。 %>
          <li><%= link_to "リストを作成", new_list_path, class: "nav-link listNew" %></li>
          <li><%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/top/index.html.erb
<div class="topPage">
  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list,  method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか？" } %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list)) %>
          </div>
        </div>
        <div class="cardWrapper">
          <div class="cardList">
            <% list.cards.rank(:row_order).each do |card| %>
              <%= content_tag "div", id: "card-#{card.id}", data: { model_name: card.class.name.underscore, update_url: list_card_sort_path(card.list, card)} do %>
                <div class="card">
                  <%= link_to list_card_path(list, card), class:"cardDetail_link" do %>
                    <div class="card_title"><%= card.title %></div>
                    <% if card.memo.size > 0 %>
                      <div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>  
          </div>      
          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "さらにカードを追加", new_list_card_path(list), class: "addCard_link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @user, url: { action: :update }, html: { class: 'listForm' }, local: true do |f| %>
      <% if @user.errors.any? %>
        <p class="text-danger">名前は1～20文字以内で入力してください</p>
      <% end %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control listName", placeholder: "名前を入力してください" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>